# Generated by Django 3.1 on 2020-09-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phoneNo', models.BigIntegerField(unique=True)),
                ('address', models.CharField(default='null', max_length=50)),
                ('emailId', models.EmailField(max_length=100)),
                ('state', models.CharField(default='null', max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('confirmPassword', models.CharField(max_length=100)),
                ('aadharNo', models.BigIntegerField(unique=True)),
                ('gender', models.CharField(default='null', max_length=100)),
                ('pincode', models.IntegerField()),
                ('district', models.CharField(default='null', max_length=50)),
                ('country', models.CharField(default='null', max_length=100)),
                ('dateOfBirth', models.DateField(default='2000-05-21', max_length=50)),
            ],
        ),
    ]
