# Generated by Django 3.1 on 2020-09-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer_registration',
            name='pincode',
            field=models.IntegerField(default=431001),
            preserve_default=False,
        ),
    ]
